# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true

# ? FORÇAR JAVA 17 (ADICIONE ESTAS LINHAS)
org.gradle.java.home=C:\\Program Files\\Java\\jdk-20
# OU se estiver usando o JDK do Android Studio:
# org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr